language: python
python:
  - 3.6
addons:
  apt:
    packages:
    - git
    - make
    - curl
    - xz-utils
    - file
    - pandoc
    - libboost-all-dev
    - ibus-mozc
    - gcc-5
    - g++-5
    - build-essential
    sources:
    - ubuntu-toolchain-r-test
before_install:
  - sudo apt-get update -qq
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 1
  - export CC="gcc-5"
  - export CXX="g++-5"
  - export CFLAGS=-std=c++11
  - export CXXFLAGS=-std=c++11
  - wget -O juman7.0.1.tar.bz2 "http://nlp.ist.i.kyoto-u.ac.jp/DLcounter/lime.cgi?down=http://nlp.ist.i.kyoto-u.ac.jp/nl-resource/juman/juman-7.01.tar.bz2&name=juman-7.01.tar.bz2"
  - bzip2 -dc juman7.0.1.tar.bz2  | tar xvf -
  - cd juman-7.01 && sudo ./configure && sudo make && sudo make install
  - sudo ldconfig
  - echo 'インストール後のテスト' | juman
  - cd ../ && pwd
install:
  - python --version
script:
  - make
notifications:
  email:
    recipients:
      - kensuke.mit@gmail.com
    on_success: always
    on_failure: always