sudo : required
language: python
python:
  - 3.5
addons:
  apt:
    packages:
    - git
    - make
    - curl
    - xz-utils
    - file
    - pandoc
    - libboost-all-dev
    - ibus-mozc
    - gcc-5
    - g++-5
    - build-essential
    sources:
    - ubuntu-toolchain-r-test
before_install:
  - sudo apt-get update -qq
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 1
  - export CC="gcc-5"
  - export CXX="g++-5"
  - export CFLAGS=-std=c++11
  - export CXXFLAGS=-std=c++11
  # install python with miniconda
  - sudo wget https://repo.continuum.io/miniconda/Miniconda3-4.4.10-Linux-x86_64.sh -O miniconda.sh;
  - sudo bash miniconda.sh -b -p $HOME/miniconda
  - sudo export PATH="$HOME/miniconda/bin:$PATH"
  - sudo hash -r
  - sudo conda config --set always_yes yes --set changeps1 no
  - sudo conda update -q conda
  # Useful for debugging any issues with conda
  - sudo conda info -a
  - sudo conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - sudo source activate test-environment
  # check python version
  - sudo python --version
  # install juman
  - wget -O juman7.0.1.tar.bz2 "http://nlp.ist.i.kyoto-u.ac.jp/DLcounter/lime.cgi?down=http://nlp.ist.i.kyoto-u.ac.jp/nl-resource/juman/juman-7.01.tar.bz2&name=juman-7.01.tar.bz2"
  - bzip2 -dc juman7.0.1.tar.bz2  | tar xvf -
  - cd juman-7.01 && sudo ./configure && sudo make && sudo make install
  - sudo ldconfig
  - echo 'インストール後のテスト' | juman
  - cd ../ && pwd
install:
  # re check python version
  - sudo python --version
script:
  - sudo make
notifications:
  email:
    recipients:
      - kensuke.mit@gmail.com
    on_success: always
    on_failure: always